name: Publish release

permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., v1.2.3)"
        required: true
      release_notes:
        description: "Release notes (markdown)"
        required: false
        default: ""

jobs:
  update_changelog:
    if: ${{ github.event_name == 'release' || github.event.inputs.tag != '' }}
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.release.tag_name || github.event.inputs.tag }}
      RELEASE_NOTES: ${{ github.event.release.body || github.event.inputs.release_notes }}
      # 👉 Make gh CLI happy:
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update CHANGELOG.md and config.json
        run: |
          set -euo pipefail
          RELEASE_NOTES="${RELEASE_NOTES:-No release notes provided.}"

          git checkout -b "automated/update-changelog-${TAG}"

          { printf "# Release %s\n\n%s\n\n" "$TAG" "$RELEASE_NOTES"; cat CHANGELOG.md; } > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md

          jq --arg tag "$TAG" '.version = $tag' config.json > config.tmp
          mv config.tmp config.json

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md config.json
          git commit -m "chore: update changelog for release ${TAG}"
          git push --set-upstream origin "automated/update-changelog-${TAG}"

          # gh uses GH_TOKEN set above
          gh pr create \
            --title "chore: update changelog for release ${TAG}" \
            --body "This PR updates the changelog."

          gh pr merge "automated/update-changelog-${TAG}" --merge

  publish_release:
    if: ${{ github.event_name == 'release' || github.event.inputs.tag != '' }}
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.release.tag_name || github.event.inputs.tag }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - { docker_name: amd64, hass_name: amd64 }
          - { docker_name: arm64, hass_name: aarch64 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.arch.docker_name }}
          build-args: |
            BUILD_VERSION=${{ env.TAG }}
            BUILD_ARCH=${{ matrix.arch.hass_name }}
          tags: |
            ghcr.io/dtidey/hass-n8n-${{ matrix.arch.hass_name }}:${{ env.TAG }}
            ghcr.io/dtidey/hass-n8n-${{ matrix.arch.hass_name }}:latest
