name: Build pull request

permissions: write-all

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          npm i
          npx playwright install
          npm run test:e2e
        working-directory: tests
          
      - name: Enable auto-merge using GitHub CLI
        if: github.actor == 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --auto \
            --squash
