name: Update CHANGELOG

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'config.json'

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog from pull requests
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: ${{ secrets.CR_PAT }}
          version-file: ./config.json
          release-count: 10
          git-push: false
          skip-commit: true

      - name: Create and merge changelog PR
        env:
          GH_TOKEN: ${{ secrets.CR_PAT }}
        run: |
          # create new GIT branch
          git checkout -b automated/update-changelog-${{ github.run_id }}

          # commit changelog
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG"
          git push --set-upstream origin automated/update-changelog-${{ github.run_id }}
          
          # create PR
          gh pr create \
            --title "Update CHANGELOG" \
            --body "This PR updates the changelog."

          # merge PR
          gh pr merge automated/update-changelog-${{ github.run_id }} --merge