name: Update CHANGELOG

on:
  release:
    types: [published]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update CHANGELOG.md with release notes
        run: |
          # Extract tag and release notes from the event payload
          TAG=$(jq -r '.release.tag_name' "$GITHUB_EVENT_PATH")
          RELEASE_NOTES=$(jq -r '.release.body' "$GITHUB_EVENT_PATH")
          
          # Ensure CHANGELOG.md exists
          [ -f CHANGELOG.md ] || touch CHANGELOG.md

          # Prepend new release info to the existing CHANGELOG.md
          { echo -e "# Release ${TAG}\n\n${RELEASE_NOTES}\n\n"; cat CHANGELOG.md; } > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md
  
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        run: |
          # put new version into config.json
          jq --arg tag "$TAG" '.version = $tag' config.json > config.tmp
          mv config.tmp config.json

          # Re-read the tag in this step
          TAG=$(jq -r '.release.tag_name' "$GITHUB_EVENT_PATH")
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git add config.json
          git commit -m "chore: update changelog for release ${TAG}"
          git push